# %.pdf:
# 	curl -o "$@" -g --create-dirs "https://kconrad.math.uconn.edu/blurbs/$@"

grouptheory/SL_2_R_.pdf: grouptheory/SL(2,R).pdf
	cp "$<" "$@"

grouptheory/SL_2_Z_.pdf: grouptheory/SL(2,Z).pdf
	cp "$<" "$@"

linmultialg/sumsquareQF_T_.pdf: linmultialg/sumsquareQF(T).pdf
	cp "$<" "$@"

gradnumthy/ostrowskiQ_i_.pdf: gradnumthy/ostrowskiQ(i).pdf
	cp "$<" "$@"

gradnumthy/ostrowskiF_T_.pdf: gradnumthy/ostrowskiF(T).pdf
	cp "$<" "$@"

#gradnumthy/x3-2y3_1.pdf: gradnumthy/x3-2y3=1.pdf
#	cp "$<" "$@"

source_proofs= proofs/writingtips.pdf \
proofs/induction.pdf \
proofs/binomcoeffintegral.pdf \
proofs/welldefined.pdf

source_grouptheory= grouptheory/whygroups.pdf \
grouptheory/sign.pdf \
grouptheory/15puzzle.pdf \
grouptheory/order.pdf \
grouptheory/cyclicgp.pdf \
grouptheory/countsubgpZpaZpb.pdf \
grouptheory/cyclicmodp.pdf \
grouptheory/coset.pdf \
grouptheory/quotientgroups.pdf \
grouptheory/homomorphisms.pdf \
grouptheory/isomorphisms.pdf \
grouptheory/A4noindex2.pdf \
grouptheory/groupsorder4and6.pdf \
grouptheory/group12.pdf \
grouptheory/groupsp2.pdf \
grouptheory/groupsp3.pdf \
grouptheory/group16.pdf \
grouptheory/genquat.pdf \
grouptheory/genset.pdf \
grouptheory/conjclass.pdf \
grouptheory/2parametergroup.pdf \
grouptheory/dihedral.pdf \
grouptheory/dihedral2.pdf \
grouptheory/isometrycpx.pdf \
grouptheory/isometryR2.pdf \
grouptheory/isometryRn.pdf \
grouptheory/SL_2_R_.pdf \
grouptheory/SL_2_Z_.pdf \
grouptheory/cauchypf.pdf \
grouptheory/cauchyapp.pdf \
grouptheory/finite-abelian.pdf \
grouptheory/gpaction.pdf \
grouptheory/transitive.pdf \
grouptheory/sylowpf.pdf \
grouptheory/sylowapp.pdf \
grouptheory/sylowmore.pdf \
grouptheory/allgrouporderncyclic.pdf \
grouptheory/Ansimple.pdf \
grouptheory/PSLnsimple.pdf \
grouptheory/charthy.pdf \
grouptheory/charthyshort.pdf \
grouptheory/semidirect-product.pdf \
grouptheory/subgpseries1.pdf \
grouptheory/subgpseries2.pdf \
grouptheory/splittinggp.pdf \
grouptheory/schurzass.pdf \
grouptheory/relativity.pdf \
grouptheory/CstarqZ.pdf \
grouptheory/maschke.pdf \
grouptheory/affineheisrep.pdf \
grouptheory/irrepdeg.pdf \
grouptheory/wordproblem.pdf

source_ringtheory=ringtheory/divthm.pdf \
ringtheory/countroots.pdf \
ringtheory/ringdefs.pdf \
ringtheory/ideals.pdf \
ringtheory/irredtestsoverQ.pdf \
ringtheory/reducibleallp.pdf \
ringtheory/irredselmerpoly.pdf \
ringtheory/gaussnormlemma.pdf \
ringtheory/euclideanrk.pdf \
ringtheory/noetherian-ring.pdf \
galoistheory/symmfunction.pdf \
ringtheory/ufdapp.pdf \
ringtheory/polynomial-properties.pdf \
ringtheory/maxideal-polyring.pdf \
ringtheory/primvector.pdf \
zorn1.pdf \
ringtheory/algebras.pdf \
ringtheory/quaternionalg.pdf

source_linmultialg=linmultialg/dimension.pdf \
linmultialg/minpolyandappns.pdf \
linmultialg/simulcomm.pdf \
linmultialg/potdiagonalizable.pdf \
linmultialg/semisimple.pdf \
linmultialg/diffeqdim.pdf \
linmultialg/linearrecursion.pdf \
linmultialg/matrixnorm.pdf \
linmultialg/descentPythag.pdf \
linmultialg/pfister.pdf \
linmultialg/hurwitzlinear.pdf \
linmultialg/hurwitzrepnthy.pdf \
linmultialg/sumsquareQF_T_.pdf \
linmultialg/moduleintro.pdf \
linmultialg/modulesoverPID.pdf \
linmultialg/alignedbases.pdf \
linmultialg/stablyfree.pdf \
linmultialg/noetherianmod.pdf \
linmultialg/dualmod.pdf \
linmultialg/dualspaceinfinite.pdf \
linmultialg/bilinearform.pdf \
linmultialg/univid.pdf \
linmultialg/univid2.pdf \
linmultialg/splittingmodules.pdf \
linmultialg/complexification.pdf \
linmultialg/tensorprod.pdf \
linmultialg/tensorprod2.pdf \
linmultialg/extmod.pdf \
linmultialg/extmodbaseextn.pdf

source_galoistheory=galoistheory/rootirred.pdf \
galoistheory/numbersoncircle.pdf \
galoistheory/simpleradical.pdf \
galoistheory/finitefields.pdf \
galoistheory/tracenorm.pdf \
galoistheory/tracenorm2.pdf \
galoistheory/separable1.pdf \
galoistheory/perfect.pdf \
galoistheory/algclosure.pdf \
galoistheory/algclosureshorter.pdf \
zorn2.pdf \
galoistheory/splittingfields.pdf \
galoistheory/separable2.pdf \
galoistheory/splittingisom.pdf \
galoistheory/galoiscorr.pdf \
galoistheory/galoiscorrexamples.pdf \
galoistheory/galoisappn.pdf \
galoistheory/galoisaspermgp.pdf \
galoistheory/galoiscorrthms.pdf \
galoistheory/cubicquartic.pdf \
galoistheory/cubicquarticallchar.pdf \
galoistheory/cyclotomic.pdf \
galoistheory/galoisSnAn.pdf \
galoistheory/linearchar.pdf \
galoistheory/artinschreier.pdf \
galoistheory/galoisdescent.pdf

source_ugradnumthy=ugradnumthy/divthmZF[T].pdf \
ugradnumthy/divgcd.pdf \
ugradnumthy/divnobezout.pdf \
ugradnumthy/modarith.pdf \
ugradnumthy/modarithshort.pdf \
ugradnumthy/uniquefactnZF[T].pdf \
ugradnumthy/analogypoly.pdf \
ugradnumthy/universaldivtest.pdf \
ugradnumthy/pythagtriple.pdf \
ugradnumthy/fermatlittletheorem.pdf \
ugradnumthy/fermattest.pdf \
ugradnumthy/eulerthm.pdf \
ugradnumthy/ordersmodm.pdf \
ugradnumthy/RSAnotes.pdf \
ugradnumthy/crt.pdf \
ugradnumthy/carmichaelkorselt.pdf \
ugradnumthy/minus1squaremodp.pdf \
ugradnumthy/infinitudeofprimes.pdf \
ugradnumthy/prime-patterns-1.pdf \
ugradnumthy/squaresandinfmanyprimes.pdf \
ugradnumthy/primestopology.pdf \
ugradnumthy/solovaystrassen.pdf \
ugradnumthy/millerrabin.pdf \
ugradnumthy/irredtestFpT.pdf \
ugradnumthy/pelleqn1.pdf \
ugradnumthy/pelleqn2.pdf \
ugradnumthy/contfrac-neg-invert.pdf \
ugradnumthy/Zinotes.pdf \
ugradnumthy/quadraticundergrad.pdf \
ugradnumthy/Picksumofsq.pdf \
ugradnumthy/descent.pdf \
ugradnumthy/descentbyeuler.pdf \
ugradnumthy/congnumber.pdf \
ugradnumthy/3squarearithprog.pdf \
ugradnumthy/4squarearithprog.pdf \
ugradnumthy/QuadraticResiduePatterns.pdf \
ugradnumthy/QRcharp.pdf \
ugradnumthy/QRchar2.pdf

source_gradnumthy=gradnumthy/mordelleqn1.pdf \
gradnumthy/quadraticgrad.pdf \
gradnumthy/idealfactor.pdf \
gradnumthy/dedekindf.pdf \
gradnumthy/dedekind-index-thm.pdf \
gradnumthy/disc.pdf \
gradnumthy/totram.pdf \
gradnumthy/nopowerbasis.pdf \
gradnumthy/integersradical.pdf \
gradnumthy/notfree.pdf \
gradnumthy/classgroupKronecker.pdf \
gradnumthy/classgpex.pdf \
gradnumthy/relativeintandidealclasses.pdf \
gradnumthy/SL2classno.pdf \
gradnumthy/matrixconj.pdf \
gradnumthy/unittheorem.pdf \
gradnumthy/chevalleyunit.pdf \
gradnumthy/frobeniuspf.pdf \
gradnumthy/galois-Q-factor-mod-p.pdf \
gradnumthy/chebappn.pdf \
gradnumthy/dirichleteuclid.pdf \
gradnumthy/schurtheorem.pdf \
gradnumthy/galoisselmerpoly.pdf \
gradnumthy/different.pdf \
gradnumthy/conductor.pdf \
gradnumthy/Gauss-Jacobi-sums.pdf \
gradnumthy/LfunctionGaussJacobi.pdf \
gradnumthy/Qw2.pdf \
gradnumthy/Qw3.pdf \
gradnumthy/Qw5.pdf \
gradnumthy/Qw6.pdf \
gradnumthy/Qw7.pdf \
gradnumthy/ostrowskiQ.pdf \
gradnumthy/ostrowskiQ_i_.pdf \
gradnumthy/ostrowskiF_T_.pdf \
gradnumthy/ostrowskinumbfield.pdf \
gradnumthy/rationalsinQp.pdf \
gradnumthy/binomialcoeffpadic.pdf \
gradnumthy/padicharmonicsum.pdf \
gradnumthy/hensel.pdf \
gradnumthy/multivarhensel.pdf \
gradnumthy/equivabsvalues.pdf \
gradnumthy/equivnorms.pdf \
gradnumthy/localglobal.pdf \
gradnumthy/primepowerunitsandGLnQ.pdf \
gradnumthy/characterQ.pdf \
gradnumthy/autRandQp.pdf \
gradnumthy/infseriespadic.pdf \
gradnumthy/mahlerexpansions.pdf \
gradnumthy/strassmannapplication.pdf \
gradnumthy/x3-2y3=1.pdf \
gradnumthy/AHrootofunity.pdf \
gradnumthy/GLnQpbar.pdf \
gradnumthy/loccptascoli.pdf \
gradnumthy/selmerexample.pdf \
gradnumthy/kummer.pdf \
gradnumthy/fltreg.pdf \
gradnumthy/carlitz.pdf \
gradnumthy/cfthistory.pdf

source_analysis=analysis/growth.pdf \
analysis/sumest.pdf \
analysis/asymp.pdf \
analysis/stirling.pdf \
analysis/gaussianintegral.pdf \
analysis/diffunderint.pdf \
analysis/series.pdf \
analysis/logarctan.pdf \
analysis/TaylorRemainder.pdf \
analysis/abelthm.pdf \
analysis/series_acceleration.pdf \
analysis/arclengthIntbypartsPi.pdf \
analysis/irrational.pdf \
analysis/entropypost.pdf \
analysis/metricspaces.pdf \
analysis/contraction.pdf \
analysis/contraction2.pdf \
analysis/sequencespaceto0.pdf \
analysis/lpspace.pdf

source_fundthmalg=fundthmalg/fundthmalgcalculus.pdf \
fundthmalg/fundthmalglinear.pdf \
fundthmalg/propermaps.pdf

source_topology=topology/connnotpathconn.pdf \
topology/finite-dim-TVS.pdf


kConrad.html:
	curl -o "$@" -g --create-dirs "https://kconrad.math.uconn.edu/blurbs/"

index_cleaned.txt: kConrad.html
	sed '1,/<table/d;/-- Start of/d' $< > $@

concat_proofs.pdf: $(source_proofs)
	gs -dNOPAUSE -sDEVICE=pdfwrite -dNO_PDFMARK_OUTLINES -sOUTPUTFILE=$@ -dBATCH $^

bookmark_proofs.info: $(source_proofs)
	./combine_pdf_bookmark.py $^ > $@

concat_grouptheory.pdf: $(source_grouptheory)
	gs -dNOPAUSE -sDEVICE=pdfwrite -dNO_PDFMARK_OUTLINES -sOUTPUTFILE=$@ -dBATCH $^

bookmark_grouptheory.info: $(source_grouptheory)
	./combine_pdf_bookmark.py $^ > $@

concat_ringtheory.pdf: $(source_ringtheory)
	gs -dNOPAUSE -sDEVICE=pdfwrite -dNO_PDFMARK_OUTLINES -sOUTPUTFILE=$@ -dBATCH $^

bookmark_ringtheory.info: $(source_ringtheory)
	./combine_pdf_bookmark.py $^ > $@

concat_linmultialg.pdf: $(source_linmultialg)
	gs -dNOPAUSE -sDEVICE=pdfwrite -dNO_PDFMARK_OUTLINES -sOUTPUTFILE=$@ -dBATCH $^

bookmark_linmultialg.info: $(source_linmultialg)
	./combine_pdf_bookmark.py $^ > $@

concat_galoistheory.pdf: $(source_galoistheory)
	gs -dNOPAUSE -sDEVICE=pdfwrite -dNO_PDFMARK_OUTLINES -sOUTPUTFILE=$@ -dBATCH $^

bookmark_galoistheory.info: $(source_galoistheory)
	./combine_pdf_bookmark.py $^ > $@

concat_analysis.pdf: $(source_analysis)
	gs -dNOPAUSE -sDEVICE=pdfwrite -dNO_PDFMARK_OUTLINES -sOUTPUTFILE=$@ -dBATCH $^

bookmark_analysis.info: $(source_analysis)
	./combine_pdf_bookmark.py $^ > $@

concat_fundthmalg.pdf: $(source_fundthmalg)
	gs -dNOPAUSE -sDEVICE=pdfwrite -dNO_PDFMARK_OUTLINES -sOUTPUTFILE=$@ -dBATCH $^

bookmark_fundthmalg.info: $(source_fundthmalg)
	./combine_pdf_bookmark.py $^ > $@

concat_ugradnumthy.pdf: $(source_ugradnumthy)
	gs -dNOPAUSE -sDEVICE=pdfwrite -dNO_PDFMARK_OUTLINES -sOUTPUTFILE=$@ -dBATCH $^

bookmark_ugradnumthy.info: $(source_ugradnumthy)
	./combine_pdf_bookmark.py $^ > $@

concat_gradnumthy.pdf: $(source_gradnumthy)
	gs -dNOPAUSE -sDEVICE=pdfwrite -dNO_PDFMARK_OUTLINES -sOUTPUTFILE=$@ -dBATCH $^

bookmark_gradnumthy.info: $(source_gradnumthy)
	./combine_pdf_bookmark.py $^ > $@

concat_topology.pdf: $(source_topology)
	gs -dNOPAUSE -sDEVICE=pdfwrite -dNO_PDFMARK_OUTLINES -sOUTPUTFILE=$@ -dBATCH $^

bookmark_topology.info: $(source_topology)
	./combine_pdf_bookmark.py $^ > $@

kconrad_%.pdf: bookmark_%.info concat_%.pdf
	gs -sDEVICE=pdfwrite -q -dBATCH -dNOPAUSE -sOutputFile=$@ $^

%-crop.pdf: %.pdf
	podofobox $< $@ media 10500 7000 46500 65000

.PHONY: all

all: kconrad_proofs-crop.pdf kconrad_grouptheory-crop.pdf kconrad_ringtheory-crop.pdf \
kconrad_linmultialg-crop.pdf kconrad_galoistheory-crop.pdf \
kconrad_ugradnumthy-crop.pdf kconrad_gradnumthy-crop.pdf \
kconrad_analysis-crop.pdf kconrad_fundthmalg-crop.pdf kconrad_topology-crop.pdf
	gs -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=$@ -dBATCH $^
